# The URL the site will be built for
base_url = "https://hardcore-goldwasser-d94311.netlify.app/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The site theme to use.
theme = "DeepThought"

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false


taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# Put all your custom variables here
navbar_items = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/data_structure", name = "Data Structure" },
	{ url = "$BASE_URL/posts", name = "Posts" },
    { url = "$BASE_URL/projects", name = "Side Projects" },
	{ url = "$BASE_URL/tags", name = "Tags" },
	{ url = "$BASE_URL/categories", name = "Categories" },
]

[extra.social]
github = "bds0900"
linkedin = "doosan-beak"


[extra.author]
name = "Doosan"
avatar = "/images/avatar.png"

